# Generated by Django 4.2.11 on 2024-03-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('bio', models.TextField()),
                ('image1_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image2_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image3_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image4_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image5_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image6_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('pronouns', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('favorite_books', models.TextField(blank=True, null=True)),
                ('favorite_movies', models.TextField(blank=True, null=True)),
                ('favorite_music', models.TextField(blank=True, null=True)),
                ('favorite_food', models.TextField(blank=True, null=True)),
                ('favorite_drinks', models.TextField(blank=True, null=True)),
                ('favorite_places', models.TextField(blank=True, null=True)),
                ('relationship_status', models.CharField(blank=True, max_length=20, null=True)),
                ('looking_for', models.TextField(blank=True, null=True)),
                ('sexual_orientation', models.CharField(blank=True, max_length=20, null=True)),
                ('height', models.CharField(blank=True, max_length=10, null=True)),
                ('body_type', models.CharField(blank=True, max_length=20, null=True)),
                ('children', models.CharField(blank=True, max_length=20, null=True)),
                ('religion', models.CharField(blank=True, max_length=20, null=True)),
                ('smoking', models.CharField(blank=True, max_length=20, null=True)),
                ('drugs', models.CharField(blank=True, max_length=20, null=True)),
                ('alcohol', models.CharField(blank=True, max_length=20, null=True)),
                ('zodiac_sign', models.CharField(blank=True, max_length=20, null=True)),
                ('languages', models.TextField(blank=True, null=True)),
                ('pets', models.TextField(blank=True, null=True)),
                ('political_views', models.TextField(blank=True, null=True)),
                ('personality', models.TextField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, max_length=20, null=True)),
                ('interests', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
