# Generated by Django 4.2.11 on 2024-04-07 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('bio', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('pronouns', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('relationship_status', models.CharField(blank=True, max_length=100, null=True)),
                ('looking_for', models.CharField(blank=True, max_length=100, null=True)),
                ('sexuality', models.CharField(blank=True, max_length=50, null=True)),
                ('height', models.CharField(blank=True, max_length=10, null=True)),
                ('body_type', models.CharField(blank=True, max_length=50, null=True)),
                ('children', models.CharField(blank=True, max_length=50, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('smoking', models.CharField(blank=True, max_length=50, null=True)),
                ('drugs', models.CharField(blank=True, max_length=50, null=True)),
                ('alcohol', models.CharField(blank=True, max_length=50, null=True)),
                ('zodiac_sign', models.CharField(blank=True, max_length=50, null=True)),
                ('pets', models.CharField(blank=True, max_length=50, null=True)),
                ('political_views', models.CharField(blank=True, max_length=50, null=True)),
                ('personality', models.CharField(blank=True, max_length=50, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=50, null=True)),
                ('hair_color', models.CharField(blank=True, max_length=50, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('meet_at', models.CharField(blank=True, max_length=50, null=True)),
                ('acceptnsfw', models.BooleanField(default=False)),
                ('hiv_status', models.CharField(blank=True, max_length=50, null=True)),
                ('prep', models.BooleanField(default=False)),
                ('last_tested', models.DateField(blank=True, null=True)),
                ('covid_vaccination', models.BooleanField(default=False)),
                ('monkeypox_vaccination', models.BooleanField(default=False)),
                ('covid_booster', models.BooleanField(default=False)),
                ('monkeypox_booster', models.BooleanField(default=False)),
                ('flu_vaccination', models.BooleanField(default=False)),
                ('hpv_vaccinations', models.BooleanField(default=False)),
                ('hepatitis_vaccinations', models.BooleanField(default=False)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('onlyfans', models.CharField(blank=True, max_length=100, null=True)),
                ('snapchat', models.CharField(blank=True, max_length=100, null=True)),
                ('tiktok', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('premium_user_account', models.BooleanField(default=False)),
                ('premium_expiry', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
