# Generated by Django 4.2.11 on 2024-03-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0007_remove_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='image7_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
