# Generated by Django 4.2.11 on 2024-03-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0008_profile_image7_profile_image7_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image1_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image2_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image3_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image4_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image5_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image6_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image7_url',
        ),
    ]
