# Generated by Django 4.2.11 on 2024-03-20 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0009_remove_profile_image1_url_remove_profile_image2_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='locationlatlong',
        ),
    ]
