# Generated by Django 4.2.11 on 2024-03-20 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0010_rename_location_profile_locationlatlong'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='locationlatlong',
            new_name='location',
        ),
    ]
