# Generated by Django 4.2.11 on 2024-03-22 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0012_alter_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='company',
        ),
    ]
