# Generated by Django 4.2.11 on 2024-03-22 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0013_remove_profile_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_books',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite_drinks',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite_food',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite_movies',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite_music',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite_places',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hobbies',
        ),
    ]
