# Generated by Django 4.2.11 on 2024-03-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0015_remove_profile_education_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='sexual_orientation',
            new_name='sexuality',
        ),
        migrations.AlterField(
            model_name='profile',
            name='alcohol',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='drugs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personality',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pets',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='political_views',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='smoking',
            field=models.BooleanField(default=False),
        ),
    ]
