# Generated by Django 4.2.11 on 2024-03-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0017_alter_profile_alcohol_alter_profile_body_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='vaccinations',
        ),
        migrations.AddField(
            model_name='profile',
            name='covid_booster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='covid_vaccinations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='flu_vaccinations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='hepatitis_vaccinations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='hpv_vaccinations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='monkeypox_booster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='monkeypox_vaccinations',
            field=models.BooleanField(default=False),
        ),
    ]
