# Generated by Django 4.2.11 on 2024-03-24 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0019_rename_covid_vaccinations_profile_covid_vaccination_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='flu_vaccinations',
            new_name='flu_vaccination',
        ),
    ]
