# Generated by Django 4.2.11 on 2024-03-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='flaged',
            field=models.BooleanField(default=False),
        ),
    ]
