# Generated by Django 4.2.11 on 2024-03-31 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_flaged'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
