# Generated by Django 4.2.11 on 2024-04-01 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_receiver_name_message_sender_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='flaged',
            new_name='flagged',
        ),
    ]
