# Generated by Django 4.2.11 on 2024-03-27 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeduserids',
            name='liked_user_id',
        ),
        migrations.RemoveField(
            model_name='wholikesmeids',
            name='who_likes_me_id',
        ),
    ]
