# Generated by Django 4.2.11 on 2024-03-27 21:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likes', '0002_remove_likeduserids_liked_user_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikedUserIds',
            new_name='LikedUsers',
        ),
        migrations.RenameModel(
            old_name='WhoLikesMeIds',
            new_name='UserswhoLikeMe',
        ),
    ]
