# Generated by Django 4.2.11 on 2024-03-28 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0004_rename_likedusers_whoilike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='wholikesme',
            new_name='UserswhoLikeMe',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='likes',
            new_name='WhoILike',
        ),
    ]
