# Generated by Django 4.2.11 on 2024-03-28 15:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likes', '0005_rename_wholikesme_like_userswholikeme_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='Like_Management',
        ),
    ]
