# Generated by Django 4.2.11 on 2024-03-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0007_alter_like_management_userswholikeme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like_management',
            name='UserswhoLikeMe',
        ),
    ]
