# Generated by Django 4.2.11 on 2024-03-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0010_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='like',
            name='wholikesme',
        ),
        migrations.AddField(
            model_name='like',
            name='user_liked',
            field=models.ManyToManyField(blank=True, related_name='user_liked', to='likes.likedusers'),
        ),
        migrations.DeleteModel(
            name='UserswhoLikeMe',
        ),
    ]
