# Generated by Django 4.2.11 on 2024-03-28 22:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likes', '0011_remove_like_likes_remove_like_wholikesme_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikedUsers',
            new_name='LikedUser',
        ),
    ]
