# Generated by Django 4.2.11 on 2024-03-28 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likes', '0012_rename_likedusers_likeduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user_liked',
        ),
        migrations.AddField(
            model_name='like',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LikedUser',
        ),
    ]
