# Generated by Django 4.2.11 on 2024-04-07 20:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('upgradeaccount', '0002_remove_upgradeorder_original_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgradeorder',
            name='order_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
